name: Deploy ke Docker Hub & VPS

on:
  push:
    tags:
      - "v*"

jobs:
  build-dan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Login ke Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}

      - name: Build dan Push
        run: |
          VERSION=${{ github.ref_name }}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bank-app:$VERSION .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bank-app:$VERSION

          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/bank-app:$VERSION ${{ secrets.DOCKERHUB_USERNAME }}/bank-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bank-app:latest

  deploy-ke-vps:
    needs: build-dan-push
    runs-on: ubuntu-latest
    steps:
      - name: Eksekusi Remote SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/bank-app:latest

            docker stop bank-app-vps || true
            docker rm bank-app-vps || true

            docker run -d \
              -p 127.0.0.1:8080:5000 \
              --name bank-app-vps \
              --restart always \
              ${{ secrets.DOCKERHUB_USERNAME }}/bank-app:latest

            docker image prune -f
