name: Deploy ke Docker Hub

on:
    push:
        tags:
            - "v*"

jobs:
    build-dan-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout kode
              uses: actions/checkout@v3

            - name: Login ke Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN}}

            - name: Build dan Push
              run: |
                  VERSION=${{ github.ref_name }}

                  docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bank-app:$VERSION .

                  docker push ${{ secrets.DOCKERHUB_USERNAME }}/bank-app:$VERSION

                  docker tag ${{ secrets.DOCKERHUB_USERNAME }}/bank-app:$VERSION ${{ secrets.DOCKERHUB_USERNAME }}/bank-app:latest
                  docker push ${{ secrets.DOCKERHUB_USERNAME }}/bank-app:latest
